name: OverTheLoom
favicon: null
layout_spectrum: 0.61013
typography_spectrum: 0.89862
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#4badac'
    - '#d37f74'
    - '#e0a7a0'
    - '#a8d4d3'
  brandStrength: 0.5856122588738799
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
